### ISSUE TITLE
Facades generated Names

### ISSUE THREAD

**Issue by marcosfreitas** [sunaoka/laravel-facade-generator#1]
I think that Facades class names should have a suffix Facade (Facades\BusinessFacade) like Service (Services\BusinessService) classes. Providers are cool like they are now (Providers\BusinessServiceProvider). Also, in laravel 8 the test class is generated automatically, maybe it should be optional.

**Comment by sunaoka** [comment]
Thank you for your suggestion.

I have released v1.3.0, which allows you to configure class name suffix and test generation.
